name: Demo workflow

on: workflow_dispatch

jobs:
  print-stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pwd
      - name: List files
        run: ls -R TodoList/TodoListApp

  build-project:
    runs-on: ubuntu-latest
    needs: print-stuff
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: '9.0.x'
      - name: List files for debugging
        run: ls -lah TodoList/TodoListApp
      - name: Build project
        run: dotnet build TodoList/TodoListApp/TodoListApp.sln
